### ISSUE TITLE
Feature Request: Salvage and mining missions

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2101]
Mining missions are self explanatory: Suitable enough for beginners. Perhaps some kind of tractor beam would be nice? Missions could be given by mining planets.

Salvage missions: A mission to retrieve a wrecked vessel. Payment is 50% of its stock cost, but the wreckage is always in a dangerous place (pirate system, empty system with large amount of pirates). It could even require to retake without destroying a certain ship from the pirates.

**Comment by KiLEdEnNis** [comment]
tractor beam? Korath Grab-Strike & Heliarch Repulsor, humans are probably not advanced enough for a tractor beam

salvage: it'd just be a disabled ship that you repair, what do you mean by wrecked? someone is working on "destroyed" ship sprites but they're just made to be destroyed to get the damaged outfits to sell, adding; 1. how would a tractor beam get a ship through hyperspace? 2. "towing" has been brought up before 3. how would you only shoot the tractor beam on the ship? why not just board them and repair them?
mining: why would someone pay you for getting them ore when you can sell them yourself as a side job?

**Comment by Tadrix** [comment]
I'll answer.
1. It wouldn't. Tractor beam is for asteroid chunks, not for ships.
2. For ships one would need some kind of tug (fighters?). For example, 1 for smaller ships (drone, fighter, interceptor, light warship, light freighter), 2 for medium warships, 5 for heavy warships and freighters. And they would only bring the disabled ship to the flagship for boarding, not do something else (for players which prefer their flagship to be a big-ass mother with weak engines).
3. I believe 1. and 2. answered this one.

Mining: Same as rush deliveries. They need certain amount of certain ore to meet their quota on time. They are willing to pay premium to get them, lest they'll have to pay bigger penalty for missing a delivery.

**Comment by jafdy** [comment]
Mining can already be done. No one has got round to doing it yet.

Salvage, repair a ship and escort it back. There is a mission like that in the FWEscort storyline.

**Comment by MessyMix** [comment]
@Tadrix I'm currently working on flavor missions for the galaxy. Hostage ship / Salvage missions in dangerous parts are included.

**Comment by KiLEdEnNis** [comment]
asteroids behave similarly to ships, being able to pull asteroids but not ships would make no sense & would probably be hard to code, for hardly any results: you can destroy the asteroids anyway

and about fighters towing a ship to you to board? that would be even harder: 1. make special bays, if not, use fighter bays on the few ships that have them, assuming a player actually bothers to get those over actual fighters, coding an AI that lets them tow a disabled ship (which would probably look bad) to you to repair it would be very hard as well, and for what? you can literally repair a ship by flying TO it

it's just too much work for too little result

**Comment by Tadrix** [comment]
@MessyMix Nice to know. :)

@KiLEdEnNis Not asteroids, asteroid _chunks_. The ones that are left when asteroid is destroyed. I believe they count as cargo? So yes, you should be able to snatch dumped cargo from ships, but not the ships themselves.

**Comment by jafdy** [comment]
I should clarify. I meant mining *missions*, not the flying around and selling what ever you catch.

**Comment by EndrosG** [comment]
@jafdy : I have a question.

Tadrix wrote:
> Mining: Same as rush deliveries. They need certain amount of certain ore to meet their quota on time. They are willing to pay premium to get them, lest they'll have to pay bigger penalty for missing a delivery.

You commented on 3 Feb • edited
> Mining (missions) can already be done. No one has got round to doing it yet.

I understand, that it is possible to create missions which require you to have a **fixed** number of specified outfits in any section. Like with the mission(s) which give you the jump drive from the Syndicate (FW campaign) or where you sell a jump drive to the Unfettered.

Jobs usually use have variable sizes. Like the delivery and bulk delivery jobs, they have a typical range but also can have some extraordinary size.
I know that Tadrix wrote "missions" and not "jobs". But I'd rather prefer to have it as repeating jobs. Because it sounds charming to have a typical size of them needing 10-25 tons of silicon, lead or iron, but sometimes ask for 134 tons or alike.
But I dont know how to realize that with the existing mechanics.
Payment-wise these missions should really pay you well. You can sell those minables at high prices. I'd need some incentive to deliver them these guys.

**Comment by Amazinite** [comment]
>I'd need some incentive to deliver them these guys.

As well as some way to make sure they don't offer in systems with that asteroid type so it makes sense why they're asking for other people to do it for them.

**Comment by DingusShingleton** [comment]
Or make it so that wherever the job is accepted, a couple other mining vessels enter the system and start targeting the valuables. If that type of asteroid isn't there, the player probably won't even notice. If it is there.... the fun's just getting started! :D

**Comment by Tadrix** [comment]
> I know that Tadrix wrote "missions" and not "jobs". But I'd rather prefer to have it as repeating jobs.

I didn't remember the difference at the time. In this thread, wherever I wrote "missions" I really meant "jobs".

**Comment by jafdy** [comment]
@EndrosG If you use a condition to remove outfits (ore) then that amount of ore will be removed even if you have more than the required amount.

**Comment by EndrosG** [comment]
@jafdy : My question still remains.

> But I'd rather prefer to have it as repeating jobs. Because it sounds charming to have a typical size of them needing 10-25 tons of silicon, lead or iron, but sometimes ask for 134 tons or alike.
> But I dont know how to realize that with the existing mechanics.
> Payment-wise these missions should really pay you well. You can sell those minables at high prices. I'd need some incentive to deliver them these guys.

I know how to remove a **fixed** number of outfits. That works like in the Jump Drive selling missions.
[MissionAction.cpp Line 137](https://github.com/endless-sky/endless-sky/tree/master/source/MissionAction.cpp#L137)

That is, having some sort of
```
mission "Titanium to Zug [0]"
	job
	repeat
	name "Titanium shortage on Zug"
	description "Mine 35 tons of titanium and deliver it to the shipyard on <destination> by <date>. Payment is <payment>."
	deadline
	source "Zug"
	on complete
		outfit "Titanium" -35
# comment: 20k + 3k * 35 = 125k
		payment 125000
		dialog "As you land, a shift manager from the shipyard thankfully takes over your mined Titanium and pays you <payment>."
```

But what - upon my understanding - @Tadrix is looking for, and what I would like to contribute, looks more like the following. And I dont see that this could work right now, for the reasons stated below.
```
mission "Titanium shortage [0]"
	job
	repeat
	name "Titanium shortage on <planet>"
	description "Mine <cargo> and deliver it to the shipyard on <destination>. Payment is <payment>"
	deadline
	cargo Titanium -25 -2 .05
	source
		attributes shipyard
	on complete
		payment 20000 3000
		dialog "You drop off your mined <commodity> and collect your payment of <payment>."
```

Difference: fixed vs. dynamic amount cargo size, fixed vs. dynamin payment.
Note that I defined the cargo with negative numbers just to make some sort of difference to the current jobs, which will give you the cargo right upon accept.
I thought about having a positive cargo amount and doing some
```
	on accept
		outfit Titanium -<tonsNumber>
```
but this would fail for three reasons:
- [ ] 1. we dont have `<tonsNumber>` yet - I have request #2351 for that
- [ ] 2. the "outfit Titanium" line is not part of a conversation, thus would not get replaced. Again, request #2351 covers that.
- [ ] 3. the job would immediately fail because the player would be missing the mission (job) cargo. As if you would have lost the ship carrying it. Mission failed.

minor:
- [ ] 4. #2359 asks to mark shipyards in map.txt. We have not yet done this, thus the above filter would fail.

**Comment by jafdy** [comment]
So your question is: Can `outfits` use a variable number command? 
Answer: Not in the current code.

**Comment by Tadrix** [comment]
If outfits can't use variable numbers, then it seems that there could be several different missions, with different amounts and payment (perhaps larger amounts paying even better rates).

@EndrosG I appreciate that you're trying to look into this.

> Mining: Same as rush deliveries. They need certain amount of certain ore to meet their quota on time. They are willing to pay premium to get them, lest they'll have to pay bigger penalty for missing a delivery.

I think shortage missions should have deadlines (be rush jobs). After all, they are asking your help, because they themselves could miss a deadline otherwise.

**Comment by EndrosG** [comment]
@Tadrix : I had (unspecified) deadline tag in the mission. ;-)

**Comment by Tadrix** [comment]
@EndrosG Yes, you had. :)

For the moment, it seems that the solution would be hard-coded missions (perhaps in a separate file, mining jobs.txt, to avoid cluttering of jobs.txt file with non-random missions, with the goal to merge these when there will be a possibility to have random numbers of outfits (minables should really be goods/commodities, but whatever).

I think of something like that (for rush missions):

job offer probability | t of ore | payment (price for t of minable ×)
----:| ----:| ----:
60%	| 40	| 100
56%	| 44	| 110
53%	| 47	| 120
50%	| 50	| 130
45%	| 55	| 140
40%	| 60	| 150
37%	| 67	| 170
36%	| 70	| 180
35%	| 80	| 200
30%	| 90	| 230
30%	| 100	| 250
29%	| 110	| 300
28%	| 120	| 350
26%	| 140	| 470
25%	| 160	| 600
24%	| 180	| 720
23%	| 200	| 780
22%	| 220	| 850
21%	| 240	| 920
20%	| 280	| 1000

**Comment by EndrosG** [comment]
With the negative cargo numbers I have some enhancement stuff in mind which could solve both issues. The salvage and mining missions and the "allow overbooking" issue of #2404 .

What I was thinking about:
add some MissionAction commands "load" and "unload" and have some sort of mission flag, telling the game that for this mission it shall look for "load" and/or "unload" commands. That mission flag could be
- either the negative cargo (or passenger) amount
- a special flag

Introducing a "load" action (on stopover for the case of #2404) could then be used to explicitely define that the mission cargo is loaded onto your ships later...
Introducing an "unload" action would be useful in only some cases: if the cargo shall be onloaded before "on complete" (or "on fail"), i.e. "on stopover", "on visit" or even "on enter".

"on stopover":
Deliver some (cargo) to (stopovers) and report on (destination) where you will receive your payment and further instructions.
I see some difficulties in cases like `"Wanderers: Sestor Scanning"` where you have many stopovers* - also see the [Wiki for Triggers in Missions](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#triggers)

"on visit":
*"You have left the <npc> behind, or some of your ships (e.g. your bulk freighters or deep rivers have not reached this system yet), but we are willing to unload some of your mission cargo already to free up some of your cargo space. You will only be paid if you delivered all of the cargo before <deadline>."*

"on enter":
You deploy 90 tons of cloaked sensor drones in the Unfettered space.
For that particular usecase I have no solution yet, how to split it up into 3 "unloads" - one third during each "on enter" -- `"Wanderers: Alpha Surveillance A"` in wanderers start.txt

If no "unload" is specified, it always happens "on complete".

Mining missions would have no "load" action, because you organise the cargo (by harvesting flotsam).
The "unload" action during "on visit" would even allow for a very special usecase: You accepted that job to deliver 240 tons of silicon. But you have only 1 interceptor and 2 star barges. (i.e. some 120+ tons of cargo space). You depart, mine as much as you can carry, return with the partial delivery (on visit -> unload) and depart again to mine the rest. :-D

**Comment by Tadrix** [comment]
> For that particular usecase I have no solution yet, how to split it up into 3 "unloads"

Optional parameter?
```python
unload 30
```
would unload 30 t of mission cargo on stopover.

The only problem is, that this would affect _all_ stopovers. For missions with multiple events on the way there are invisible missions and mission chains. Obviously, not applicable to jobs, which should be one mission (unless there's an invisible one which triggers only when certain job is active, but it should be non-random one, since AFAIK there's no way for the mission to pass a random value to another mission).

**Comment by EndrosG** [comment]
In simple cases that "unload 30" could work. But do you remember those mission where you have passengers and cargo combined? I know, I think in complicate patterns...

Regarding your AFAIK: #2383 has been merged already. This allows to pass numeric values, but only for conditions. Not for actions, nor texts (like planet names, e.g. source or destination). I dont know what you had in mind with what you wrote, so I cant really comment it deeper.

**Comment by Tadrix** [comment]
I had in mind destinations, cargo/passenger amounts, etc. Inability to pass a destination doesn't allow for random multi-mission job chains.

**Comment by EndrosG** [comment]
@Tadrix: I went ahead and created pull #2449 
The mining missions inside are still pretty static, I know, but it's a beginning, given that we dont have any right now. I would be happy if you could review it.

As a rule of thumb, I made payment = <outfit price> +400 (per ton) for regular mining, and additional +200 (per ton) for "deadline 10" rush missions.
Silicon is only available in a large mining version (60 tons), because I did not want to pay double price for tiny quantities.

**Comment by Tadrix** [comment]
I took a look at it and I liked what I saw, but I thing that increase in quantities should warrant a slight exponential increase in payoff, because with large enough quantities you'll need to mine several systems. Or, at least, you could multiply ore price instead of increasing it by a fixed amount, for example, multiplying by 1,1 (ordinary) and 1,25 (rush). Ore price in theory represents how hard it is to mine, so the price increase should reward getting that specific ore on time.

**Comment by tehhowch** [comment]
While I have #3076 done with static values, I'm also implementing the same method used for random cargo selection and generation. Since my submission will be just one way to do it, and it makes some assumptions on how to handle text substitution with gifting, I'm not conditioning #3076 on its acceptance (but if accepted, #3076 can be massively improved while also requiring fewer lines).
