### ISSUE TITLE
Idea Library

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#279]
This is the assembly of all the interesting ideas in the Endless Sky issues page. Please suggest what to add and what to remove.

Posted on [G+ Page](https://plus.google.com/u/0/communities/117639896756370381065). Yes, I created a public Google Plus page for Endless Sky (Not official).
 - [ ] Megaships #234
 - [ ] Balance Atomic Engines #271 
 - [x] Comparing Outfits #240 
 - [ ] Bookmarks on the Map #237 
 - [ ] Economy changes and enchantment #275 #258
 - [ ] Missions #211
 - [ ] **MULTIPLAYER** #266 #149 
 - [ ] Modify/Change/Balance boarding mechanics #19 #42 #102 #118 #165 
 - [ ] Scale Ships #265 #234
 - [ ] Specialist Crew #259 
 - [ ] **Improve and Enchant asteroids** #257 
 - [ ] Effects #256 #254 
 - [ ] Story lines #249 
 - [ ] Modules #29 #255 #203 
 - [ ] Balance #281 #261 #264 #267 #73 #227 #195 #251 
 - [ ] Visual Improvements #282
 - [ ] Color Key for map #288 
 - [ ] Hotkeys #287 #13 #293
 - [ ] **BUGS** #286 #176 
 - [ ] Planetary Overhaul #292
 - [ ] Formations and Fleet Actions #302

**Comment by Wrzlprnft** [comment]
https://groups.google.com/forum/#!forum/endless-sky

**Comment by airtroop392** [comment]
#243 has been closed, along with #299, #79, #284's issue has been resolved but OP hasn't marked it closed, and I assume a lot more of these are either closed or resolved, but I don't have time to check each one (currently on phone).

**Comment by gchapyzh** [comment]
@airtroop392 thank you for the update!

**Comment by endless-sky** [comment]
Since the issue list itself is already a list of ideas, I don't think there's a need for a "meta-issue" like this that just lists other issues in the tracker.
