### ISSUE TITLE
Update asset directory for v0.9.9 content

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#4272]
According to gdrive, the last update to the [asset directory](https://drive.google.com/drive/folders/0B9aK8dG39P29fkdBeUJjSXJYVDdjMEpkOXh3T1NDekFYaTEtbkdTdzVwX2NTUWVVT3BUWVk) was the new Clink landscape on 22.06.2018 (d595604dc51aeee59ab3f0645bc0a165b1342a0b). Since then, lots PRs have been merged, but the assets have remained the same.

The following are required updates to the assets directory, in chronological order:

- [x] #3416: Was before the last update, but nevertheless the mosprey files are missing (thanks becca)
- [x] #3954
- [ ] #3957: **The assets in the first comment are not uptodate**, somebody will have to redo them. See [this comment](https://github.com/endless-sky/endless-sky/issues/4272#issuecomment-493437140) for details.
- [x] #3960: Assets are in #3672.
- [x] #3314
- [x] #3536
- [x] #3359
- [x] #4014 
- [x] #4056: Assets are in [the last comment](https://github.com/endless-sky/endless-sky/pull/4056#issuecomment-446449664)
- [x] #3347 
- [x] #3761 
- [x] #3120: Assets are in endless-sky/endless-sky-high-dpi#58
- [x] #3683 
- [x] #4145 
- [x] #4180 
- [x] #4203 
- [x] #4154 
- [x] #3893: Assets are in endless-sky/endless-sky-high-dpi#71
- [x] #4226
- [x] #4196: The gidfire assets are in [this comment](https://github.com/endless-sky/endless-sky/pull/4196#issuecomment-474082558), the T3 AM assets in the one right below.
- [x] #4244 
- [x] #4211 
- [x] #4250
- [x] #4256: Assets are here: [pleiades.zip](https://github.com/endless-sky/endless-sky/files/3194967/pleiades.zip)

This list is uptodate as of 2071bf10b7b54a5187333c12fb5b12bd214a1cbd.

**Comment by Zitchas** [comment]
Regarding #3761 :  I updated the asset zip file with two changes: 1) Removed the Software Scanner assets, as that was removed from the PR. 2) Added additional files to the Gull folder so it now contains all the assets instead of just the .xcf and .blend files.

I replaced/updated the zip file on google drive, so the same link should still work, but just in case, here it is again: https://drive.google.com/open?id=1Dq2TjcVHYdA9QVzSxMKnw_k5xzvhUC7m

**Comment by Amazinite** [comment]
Ref: #3120, assets are in the high DPI PR. https://github.com/endless-sky/endless-sky-high-dpi/pull/58

**Comment by MCOfficer** [comment]
I got word from Vilhelm regarding #3957. It seems that the assets he posted are no longer uptodate, and he will not have access to the files (if they exist) nor can he reconstruct them in the foreseeable future. 

<details>
<summary>Here's the relevant E-Mail(s)</summary>

> Hey MCO,
> 
> I never changed the blender assets and if I recall correctly any the
> updated [sic], changed versions were all created using one blender file per
> explosion size (or perhaps for all sizes). If they exist, it's in those
> files. If it's not there, I don't have them.
> 
> On the bright side, I remember updating those assets was made by rotating
> the flower image layer per frame, so at least you have everything needed to
> re-update the images using the assets if you need to.
> 
> Feel free to contact me if you have any more questions. Sorry I'm not able
> to do anything more - not until March 2021, anyway.  Glad to hear progress
> is still being made on E.S.
> 
> Regards,
> 
> Vilhelm

> *one GIMP file per explosion size

</details>

**Comment by Amazinite** [comment]
I don't see missing those assets as too much of an issue given that we intend on replacing them. I recall Comnom having dabbled with working on better explosions.

**Comment by Pointedstick** [comment]
For https://github.com/endless-sky/endless-sky/pull/3897, there are no assets other than the image itself. It was not post-processed at all.

**Comment by endless-sky** [comment]
I've uploaded all those assets aside from the one that was identified as not up to date.

**Comment by Pointedstick** [comment]
Done now.
