### ISSUE TITLE
Update the assets directory, round 2

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#4571]
This is a continuation/reboot/whatever of #4272. Since that update to the assets, about half a year has passed. This issue exists to keep track of all missing asset updates that need to be done. 

*Slight teaser: I've also been investigating [other methods](https://github.com/MCOfficer/lfs-assets-test) of hosting the assets, thanks to CatLady. ~~Once ready, that will receive its own issue for discussion.~~ #4620*

- [ ] #4377 (This asset link includes the subsequent update in 0f5824e50da54d261d1b6aa66fa9b8dfdd03ba83)
- [ ] #4319: Assets are in [this comment](https://github.com/endless-sky/endless-sky/pull/4319#issuecomment-497941713)
- [ ] #4455  
- [ ] #4458: Assets are in the inital post, the Star Queen assets in [this comment](https://github.com/endless-sky/endless-sky/pull/4458#issuecomment-523851976)
- [ ] #4495
- [ ] #4573
- [ ] #4563
- [ ] #4564
- [ ] #4607: Assets are here: [heliarch_shield_repair.zip](https://github.com/endless-sky/endless-sky/files/3756961/heliarch_shield_repair.zip)
- [ ] #4611
- [ ] #4594
- [ ] #4605
- [ ] #4102
- [ ] #4222
- [ ] #4546
- [ ] #4644
- [ ] #4643
- [ ] #4661
- [ ] #4689 
- [ ] #4692
- [ ] #4687
- [ ] #4622
- [ ] #4716
- [ ] #4748
- [ ] #4787
- [ ] #4782
- [ ] #4792
- [ ] #4785
- [ ] #4856
- [ ] #4876
- [ ] #4652
- [ ] #4920
- [ ] #4960
- [ ] #4948 (assets in the [last comment](https://github.com/endless-sky/endless-sky/pull/4948#issuecomment-604046908))
- [ ] #5010: [finisher storage assets.zip](https://github.com/endless-sky/endless-sky/files/4827190/finisher.storage.assets.zip)
- [ ] #5001 (No new assets - Gascraft has been renamed to Puffin)
- [ ] #5067
- [ ] #5108
- [ ] #4786
- [ ] #4662
- [ ] #5170
- [ ] #5173
- [ ] #5042: [jump drive assets.zip](https://github.com/endless-sky/endless-sky/files/5012213/jump.drive.assets.zip)
- [ ] #5198
- [ ] #4986
- [ ] Also, the Quarg assets [appear to need fixing](https://github.com/endless-sky/endless-sky/issues/4571#issuecomment-569410961)

This list is uptodate as of 990834a74d0429f920f7b2e5bb4a53b37f2af2ca.

**Comment by Cat-Lady** [comment]
Eh, any progress on this? With recent changes - like fixes to assets that were  lacking top pixel - hunting it all down becomes even more tedious.

In any case, I'm eager to continue work on baking in additive blending runner lights to all human ships, but I'm, definitely going to wait until the assets situation is fixed to manageable levels.

**Comment by Amazinite** [comment]
@endless-sky should be able to give the collaborators edit access to the Google Drive folder, which would mean that whenever we merge PRs with new assets, we'd also put those assets into the Google Drive folder.

**Comment by beccabunny** [comment]
It should also be noted that while the assets here https://github.com/endless-sky/endless-sky/pull/3536 seem to be okay, the Quarg outfits blends on the google drive are empty, except the Skylance (only the normal version), the Countermeasures and the Quantum Shield

**Comment by MCOfficer** [comment]
Would anyone be willing to continue this issue? Basically, go through all the commits after the linked one, check the PRs and link them here if they have assets. Sorry for not doing it anymore, but I've done this for all commits of the past 4 years and just can't be arsed anymore...

**Comment by tehhowch** [comment]
@MCOfficer we should develop a standalone tool (in the assets repo) that walks a commit range and extracts links to .zip, .7z, and links associated with the word "asset" from the comments and or body of any associated PRs.

**Comment by MCOfficer** [comment]
I'm *very* uncomfortable with that. Tools to extract from human text are inevitably fallible. As far as assets go, I'd rather guarantee 100% safety that we do in fact catch all assets.

Also, this feels like a costly solution to a problem that can be solved in ways other than monkeypatching. Eventually, we'd want to have some way for contributors to submit assets to whereever we store them, so collaborators **can merge them as they merge the PR**.

**Comment by quyykk** [comment]
Seems like we can close this
