### ISSUE TITLE
Checklist for unicode support

### ISSUE THREAD

**Issue by thewierdnut** [endless-sky/endless-sky#8572]
### Problem Description

Previous attempts at integrating unicode support have failed due to the complexity of the problem. 

### Related Issue Links

Previous (closed) MRs: 
- #3312
- #4123

### Desired Solution

We need to break down the monolithic MRs into bite sized merges that can be better digested. Here is the checklist that I think needs to happen (not necessarily in this order):

- [ ] Move hardcoded strings into the config files
- [ ] Create a text formatting mechanism that uses string keys that can be moved if necessary. (ie, something that can convert `"The {ship_name} is moving erratically" to "The Tattered Brute is moving erratically")
- [ ] Create a pre-rendered store mechanism for text (so any slow font parsing code only has to be executed when the text changes. This can be a backing texture or a vbo or something similar)
- [ ] Replace all text rendering with DisplayText/WrappedText or something similar.
- [ ] Update text rendering classes to allow right-to-left rendering
- [ ] Update text rendering classes to allow script-specific formatting rules (ie WrappedText doesn't need to wait for a space for line breaks when rendering chinese characgters)
- [ ] Update text rendering classes to allow handle overflow (ie truncating, ellipsis, narrow fonts, scrolling using the backing store, other possibilities)
- [ ] Integrate a font rendering library
- [ ] Design a mechanism to switch between available fonts automatically to select a font with the needed glyphs (possibly with support for the original font sprite if available)
- [ ] Implement and/or integrate a unicode bidi algorithm to handle bidirectional text (Basic support is trivial, but something like fribidi should be used if available)
- [ ] Integrate a text shaping library (harfbuzz is the only option I've found. all other libraries directly or indirectly use it)

### Alternative Approaches

Someobdy could adopt the existing MR's I suppose, depending on whether the freetype/harfbuzz approach is desired, or the full pango approach. 

### Additional Context

I am volunteering to work on this, but first I am looking for feedback on if the checklist looks complete, and what other developers think a full solution should look like.

**Comment by thewierdnut** [comment]
> > Move hardcoded strings into the config files
>
> This doesn't relate to Unicode support. You can exclude it.

I'm not sure I agree. The strings need to be in a place where they can go through unicode text processing, and right now, many of them are being passed directly to the font shader.

**Comment by thewierdnut** [comment]
Without any other input, I'm going to go ahead and create an MR with all the in-game strings extracted to a config file.

**Comment by quyykk** [comment]
> I'm not sure I agree. The strings need to be in a place where they can go through unicode text processing, and right now, many of them are being passed directly to the font shader.

I'm not sure I understand this, but then again I'm not very experienced in that part of the code base. Can't they go through unicode text processing dynamically? Because you need this anyways for dynamic messages (like player ship names) no?

Anyways, ow should the config file look like? Does using the existing structure make sense?, so maybe:

```
string "player ship destroyed"
    `Your ship {} has been destroyed`
string "player ship overheated"
    `Your ship has overheated.`
```

**Comment by thewierdnut** [comment]
> Can't they go through unicode text processing dynamically?

That basically what I'm trying to imply... Every string meant for display has to go through unicode processing. My best guess is that the optimal location for such processing will be after the string has been passed off by the game engine for rendering. 

> Does using the existing structure make sense?

That is basically what I have in mind. I found the Format::Replace() function (which is already there) that handles the formatting requirements nicely. I've created a new `labels.txt` which I am populating with lines like this:

```
label "overheat"
	`Your ship has overheated.`
label "enter system"
	`Entering the <name> system on <date>.`
```

I'm not attached to the `label` nomenclature, but I was trying to find something that didn't re-use the term "string" too much, since strings already have a clear meaning. "StringTable" might be better and more clear, but I was looking for something smaller and shorter to type in the code.

**Comment by quyykk** [comment]
> That basically what I'm trying to imply... Every string meant for display has to go through unicode processing. My best guess is that the optimal location for such processing will be after the string has been passed off by the game engine for rendering.

Then why the config file? sry I'm really not that knowledgeable here...

**Comment by thewierdnut** [comment]
It is possible to add unicode support without having all the ascii strings extracted to a config file, but it seems kind of pointless. If all of those strings are ascii, why would we need unicode support? 

I'll admit it is kind of a diamond shaped dependency, where translations (not directly addressed here) need both unicode and a string table, but the string table and unicode don't necessarily need each other. However, having a string table infrastructure in place would be nice as it informs the design of the text processing and the font renderer.

**Comment by oo13** [comment]
For translation, please consider using gettext. It's a bad idea to reinvent a new translation method. Especially, the string table method whose key is not the original text may cause the synchronization hell.

Anyway, you need not to care about the translation to support Unicode.

**Comment by thewierdnut** [comment]
I looked through gettext, and I looked through your changes, and I have a few problems with them.

1. We will need a string table even if we use gettext. Most of the strings I've extracted so far have been things like `"(Your fleet is|Your escort is|The selected escort is|The selected escorts are)(|unable and no longer|no longer) (focusing fire on "<target>"|following "<target>"|moving to the given location|moving to the given location in the <system> system|holding position|gathering around your flagship)"`. Obviously that is no good for translation as the composition of those sentences won't match grammar rules for other languages. We instead need to generate every possible string (for that example, 72 of them), place each one in the string table where they can be generated, and then in the code, generate the string *key* instead of the string contents. This actually makes the code simpler and easier to read in the examples I have edited so far. 
2. Even with gettext, the majority of translation work still involves editing the data files to edit display names, dialogue, and user interfaces. Add to that the fact that only about half of the strings I have extracted so far have looked like they fit the gettext use case, and it looks like gettext can be used for about 0.38% of your workload. 
3. Endless sky already has the ability to retrieve and format strings.  gettext doesn't really give us something new. In general, adding new dependencies to a project is a bad thing. I've seen projects where people have added every dependency under the sun to solve the problem they are facing "their" way, and they become almost impossible to maintain and port to new platforms. New dependencies should only be added as a last resort. 

I am not an endless sky developer, I'm just trying to solve a perceived problem as best I know how. I don't think anybody should waste time implementing a solution that won't be used, so I would love to hear counter-arguments and a decision from a developer. Trying to document and make decisions on a path forward is the entire reason why I started this issue. 

Having said that, I've seen projects die because people could not come to a consensus on a solution. I would rather implement the second-best solution than have no solution at all, so please, let me know what you think.

**Comment by Zireael07** [comment]
@thewierdnut raises a very good point. The way sentences are concatenated, e.g. in the hails, is basically incompatible with translating to many languages (especially those with large case systems, eg. most Slavic languages).

As both a translator and a programmer, I don't think it's possible to translate this game.

**Comment by thewierdnut** [comment]
> As both a translator and a programmer, I don't think it's possible to translate this game.

My current approach is to take every possible concatenated string, and generate a string table entry for it. Basically, the example above looks like this:
```
label "escort not focus"
	`Your escort is no longer focusing fire on "<target name>".`

label "escort not follow"
	`Your escort is no longer following "<target name>".`

label "escort not move"
	`Your escort is no longer moving to the given location.`

... 69 more strings follow ...
```

That way, a translator can change the entire text. All the game has to do is generate the label key, not the text itself. @Zireael07  what problems do you see with that approach?

**Comment by oo13** [comment]
I just said, you can ignore the translation support even if you would support Unicode.  You can support the translation, of course.

Can you discuss the translation in #558?

> As both a translator and a programmer, I don't think it's possible to translate this game.

I have no idea to translate substitution (#6356), but I can translate Endless Sky 0.9.14 into Japanese, including all phrase nodes. We discussed it in #558.

**Comment by thewierdnut** [comment]
> Can you discuss the translation in https://github.com/endless-sky/endless-sky/issues/558?

I understand your desire to keep the two issues separate, but I don't think that is possible. The needs of translation will drive the requirements of unicode support.

**Comment by tibetiroka** [comment]
I noticed there was no mention of accepting unicode input (for ship or pilot names), and for parsing these unicode strings from the data files. Is that something that is planned/desired?
 
Kind of related, but we still don't have really good keyboard layout detection, which would be needed for proper unicode input.

**Comment by thewierdnut** [comment]
> I noticed there was no mention of accepting unicode input (for ship or pilot names), and for parsing these unicode strings from the data files. Is that something that is planned/desired?

Unicode parsing from data files is already implemented. 

> Kind of related, but we still don't have really good keyboard layout detection, which would be needed for proper unicode input.
I'm reaaaalllly hoping that this will be a non-issue, but I will do some research.

**Comment by oo13** [comment]
For a text box, [SDL Text Input](https://wiki.libsdl.org/SDL2/Tutorials-TextInput) supports the East Asian languages as well as other keyboard layouts.

**Comment by ketronix-dev** [comment]
Any progress for that?
