### ISSUE TITLE
Exclude Finches and Boxwings from Fighter Bays

### ISSUE THREAD

**Issue by Just-Existing** [endless-sky/endless-sky#9226]
### Problem Description

The description for the Finch says that it barely fits into a fighter bay. My question is: Why do Finches fit into fighter bays at all? The Free Worlds does not make any ships that have fighter bays. They would have a tactical advantage if their fighters were just small enough to attach to the Hauler-F series of ships with external clamps but far too large to fit in any conventional fighter bay as produced by the Navy or the Deep.

### Related Issue Links

Could not find any open issues or PRs that discussed this.

### Desired Solution

Code should be added that causes some fighters(currently the Finch and Boxwing) to dock only with ships that have external clamps. Those fighters would have an extra attribute denoting this(Figure 1). The number of external and internal bays should be shown separately(Figure 0). 

Also, the exact mechanism for external clamps, fighter bays, and drone bays could be elaborated further in ship descriptions. The Finch should be slightly closer to the Sparrow in terms of capabilities to reflect its strategically larger size.

### Alternative Approaches

The finches could be removed completely and any interceptor or fighter would be able to fit in an external clamp. Most of the interceptors look like they might be just small enough to fit. I have wondered why the Free Worlds felt the need to redesign the Sparrow when it looks as though it might fit on the clamp anyway. This option is a little overpowered if you could just have a full size interceptor that does not even need a hyperdrive.

Alternatively, a wholly new category could be created for finches and boxwings between interceptor and fighter(Figure 2).

### Additional Context

Figure 0:
![External Clamps](https://github.com/endless-sky/endless-sky/assets/69060286/4a775fa3-9154-4c37-a644-200ed8be8543)
Figure 1:
```
ship "Finch"
	plural "Finches"
	sprite "ship/finch"
	thumbnail "thumbnail/finch"
	attributes
		category "Fighter"
		"cost" 126000
		"shields" 1100
		"hull" 200
		"required crew" 1
		"bunks" 1
		"mass" 40
		"drag" .83
		"heat dissipation" .85
		"outfit space" 110
		"weapon capacity" 20
		"engine capacity" 40
		"external only"
		weapon
			"blast radius" 12
			"shield damage" 120
			"hull damage" 60
			"hit force" 180
```
Figure 2:
```
ship "Finch"
	plural "Finches"
	sprite "ship/finch"
	thumbnail "thumbnail/finch"
	attributes
		category "Mini Interceptor"
		"cost" 126000
		"shields" 1100
		"hull" 200
		"required crew" 1
		"bunks" 1
		"mass" 40
		"drag" .83
		"heat dissipation" .85
		"outfit space" 110
		"weapon capacity" 20
		"engine capacity" 40
		weapon
			"blast radius" 12
			"shield damage" 120
			"hull damage" 60
			"hit force" 180
```
```[tasklist]
### Tasks
- [ ] Change UI to tally external clamps separate from fighter bays.
- [ ] Add attribute that disallows the ship from docking in fighter bays.
- [ ] Modify lore relating to fighter bays to explain the difference between the three types.
- [ ] Modify Finch and Boxwing stats to reflect slightly larger size.
```

**Comment by Hurleveur** [comment]
I like the idea of the external bays a lot especially bc the skein and co simply suck compared to navy carriers, this would make them different
That said since a ship able to fit inside should also fit outside, we shoud probably change the code like you suggest, should we want this.

**Comment by Zitchas** [comment]
I agree. It would be very good to differentiate internal vs external bays.

**Comment by vitalchip** [comment]
By what criteria does a Finch 'barely' fit into a bay?
It's narrower than a Barb, shorter than a Dagger, lighter than a Petrel.

Have differences between internal and external bays by all means but don't base it on a throw away line of narrative from a ship description which falls to pieces under the lightest of scrutiny.

**Comment by Just-Existing** [comment]
> By what criteria does a Finch 'barely' fit into a bay? It's narrower than a Barb, shorter than a Dagger, lighter than a Petrel.

First of all, Petrels also attach to the outside of ships. 
Secondly, maybe the model of the Finch needs to change, but the model is not exactly an engineering diagram and might have features not visible. 
Finally, Finches are heavier and have more outfit space than all other human fighters and one of the things I am suggesting is changing the stats of the Finch to fit.

**Comment by vitalchip** [comment]
Petrels fit into internal bays, as do much larger fighters.

The point I'm making is that if the Finch is to be made unable to fit into an internal bay then we had better work out why, so we know which other ships should alos not fit.

**Comment by Amazinite** [comment]
This would effectively just be a nerf to the Finch and Boxwing, or any other fighter (or drone) that we say can only use external bays, by severely limiting the number of ships it can be carried on. I don't see what we'd actually gain gameplay-wise by a change like this, as it'd further complicate carrier gameplay by requiring that you pair certain fighters with certain carriers. This also runs into UI issues in that we don't have UI space for additional ship info attributes; say a ship has external bays and internal bays, that could be up to four lines of attributes describing how many bays you have (such as what happened [here](https://github.com/endless-sky/endless-sky/pull/7597#issuecomment-1313108830)).

**Comment by Hurleveur** [comment]
We could instead do away with the drone/fighter system and put a maximum mass on bays?

**Comment by Amazinite** [comment]
No thanks. Too much complexity. How would we display that in the UI? Would we display the total tonnage of fighters your ship can carry? What if you have two 80 ton bays and a 160 ton fighter? That wouldn't fit, but how would we show that?

**Comment by Just-Existing** [comment]
Why would the Free Worlds build new manufacturing equipment for a new ship class if an existing ship class with a slightly shorter fuselage and slightly shorter wings would fit the same role? I think the added verisimilitude from changing the way the Free Worlds is fighting this war would make up for the added complexity.

Could the two lines from clamps and bays could be reduced into one like this? 
![External Clamps-Bays](https://github.com/endless-sky/endless-sky/assets/69060286/39448144-243c-4a49-8f28-5661b2a83511)

**Comment by Amazinite** [comment]
> Why would the Free Worlds build new manufacturing equipment for a new ship class if an existing ship class with a slightly shorter fuselage and slightly shorter wings would fit the same role?

1) The FW carriers aren't a new ship class, they're a modification of existing Haulers.
2) The FW have no existing ship class that carries fighters.

**Comment by Just-Existing** [comment]
>     1. The FW carriers aren't a new ship class, they're a modification of existing Haulers.
>     2. The FW have no existing ship class that carries fighters.

I was referencing the Finch, which apparently shares 85% of parts with the Sparrow. I assume that some of the remaining 15% required new manufacturing equipment to be built. If the Free Worlds were contracting these fighters, they would want to reduce that 15% as much as possible. Slightly more powerful clamps are easier to produce than entire ships, so if increasing the size of the Finch was possible, that would be done to save costs.

**Comment by Saugia** [comment]
Keep in mind we aren't changing certain parts of gameplay for the sake of realism, so referencing the parts and such isn't really a matter as it's talking more of actual physical space taken up which is something we aren't basing anything off of. I understand why you're trying to differentiate the classes and what you're basing them off of in terms of logistics, but again it's coming more off of realism, and I agree with Amazinite that this seems to be overcomplicating a part of the game that doesn't need to be for the sake of being different.

**Comment by Just-Existing** [comment]
I am closing this issue as no one seems to be interested in this and if implemented would reduce the readability of the UI without any real gameplay improvement.
